# Generated by Django 5.2.5 on 2025-08-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicePanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_file', models.FileField(upload_to='voice/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
